//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderITforGEA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Alarmy
    {[Key]
        public int Id_a { get; set; }
         [Display(Name = "Data alarmu: ")]
        public Nullable<System.DateTime> data_alarmu { get; set; }
         [Display(Name = "Typ alarmu: ")]
        public string typ_alarmu { get; set; }
         [Display(Name = "Status: ")]
        public string status { get; set; }
         [Display(Name = "Wykona³ : ")]
        public string wykonal { get; set; }
        public string ServiceGuard_id_sg { get; set; }
        public Nullable<System.DateTime> data_wykonania { get; set; }
         [Display(Name = "Numer seryjny: ")]
        public string serial_number { get; set; }
    
        public virtual ServiceGuard ServiceGuard { get; set; }
    }
}
