//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderITforGEA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Biling
    {
        public string Id_b { get; set; }
             [Display(Name = "Data: ")]
        public Nullable<System.DateTime> data { get; set; }
         [Display(Name = "Treœæ: ")]
        public string tresc { get; set; }
         [Display(Name = "U¿ytkownik: ")]
        public string login { get; set; }
        public string ServiceGuard_id_sg { get; set; }
    
        public virtual ServiceGuard ServiceGuard { get; set; }
    }
}
