//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderITforGEA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Logi
    {[Key]
        public int Id { get; set; }
        public string id_uzytkownik { get; set; }
        [Display(Name="Akcja")]
        public string co_zrobil { get; set; }
                [Display(Name = "Czas")]
        public Nullable<System.DateTime> czas { get; set; }
    }
}
