//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderITforGEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceManager
    {
        public ServiceManager()
        {
            this.ServiceGuard = new HashSet<ServiceGuard>();
        }
    
        public int Id_sm { get; set; }
        public string nr_tel { get; set; }
        public string serial { get; set; }
        public string desc { get; set; }
        public string nr_tel_temp { get; set; }
    
        public virtual ICollection<ServiceGuard> ServiceGuard { get; set; }
    }
}
