//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderITforGEA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ServiceGuard
    {
        public ServiceGuard()
        {
            this.Alarmy = new HashSet<Alarmy>();
            this.Biling = new HashSet<Biling>();
            this.Klient = new HashSet<Klient>();
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    [Display(Name = "Numer seryjny: ")]
        public string serial_number { get; set; }
           [Display(Name = "Numer karty: ")]
        public string nr_karty { get; set; }
         [Display(Name = "Numer PIN: ")]
        public Nullable<int> pin { get; set; }
         [Display(Name = "Numer telefonu: ")]
        public string nr_tel { get; set; }
        [Display(Name = "Lokalizacja: ")]
        public string lokalizacja { get; set; }
           [Display(Name = "Przedzia³ serwisowy: ")]
        public string przedzial_serwisowy { get; set; }
         [Display(Name = "Do serwisu: ")]
        public Nullable<int> do_serwisu { get; set; }
          [Display(Name = "Ostatni serwis: ")]
        public Nullable<System.DateTime> ostatni_serwis { get; set; }
            [Display(Name = "Ostatni alarm: ")]
        public Nullable<System.DateTime> ostatni_alarm { get; set; }
            [Display(Name = "Licznik SMS: ")]
        public Nullable<int> licznik_sms { get; set; }
        public Nullable<int> ServiceManager_id_sm { get; set; }
        public string user_id_u { get; set; }
            [Display(Name = "Jêzyk: ")]

        public string jezyk { get; set; }
             [Display(Name = "Firma: ")]
        public string firma { get; set; }
          [Display(Name = "Numer SuperVisor: ")]
        public string nrSuperVisor { get; set; }
         [Display(Name = "Numer ServiceCenter: ")]
        public string nrServiceCenter { get; set; }
        public string przedzial_serwisowy_temp { get; set; }
        public string serial_number_temp { get; set; }
        public Nullable<int> pin_temp { get; set; }
        public string lokalizacja_temp { get; set; }
        public Nullable<int> do_serwisu_temp { get; set; }
        public Nullable<System.DateTime> ostatni_serwis_temp { get; set; }
        public string nrSuperVisor_temp { get; set; }
        public string nrServiceCenter_temp { get; set; }
        public Nullable<System.DateTime> ostatni_alarm_temp { get; set; }
        public string jezyk_temp { get; set; }
         [Display(Name = "Aktualny czas: ")]
        public Nullable<int> aktualny_czas { get; set; }
        public Nullable<int> aktualny_czas_temp { get; set; }
    
        public virtual ICollection<Alarmy> Alarmy { get; set; }
        public virtual ICollection<Biling> Biling { get; set; }
        public virtual ICollection<Klient> Klient { get; set; }
        public virtual ServiceManager ServiceManager { get; set; }
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
    }
}
