//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderITforGEA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarmy> Alarmy { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Biling> Biling { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<ServiceGuard> ServiceGuard { get; set; }
        public virtual DbSet<ServiceManager> ServiceManager { get; set; }
        public virtual DbSet<Logi> Logi { get; set; }
        public virtual DbSet<SMS> SMS { get; set; }
    }
}
